apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.4.8
        args:
        - --source=ingress
        - --domain-filter=k8s.consort-it.de
        - --provider=aws
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id=consort-it
